### ISSUE TITLE
running on iNatural

### ISSUE THREAD

**Issue by MinaRe** [siavash-khodadadeh/MetaLearning-TF2.0#4]
Hi Siavash,

Thank you for sharing repo, How can I run the UMTRA on iNatural?

**Comment by siavash-khodadadeh** [comment]
Hello, 

I am not sure about iNatural dataset actually, can you provide a link.
Any dataset, if you make a folder for any class and put all of the instances in that folder, you should be able to call get_umtra_dataset. You also need to write an augmentation function.

**Comment by MinaRe** [comment]
https://www.kaggle.com/c/inaturalist-2019-fgvc6/data
Actually, I wanna use GAN instead of conventional data augmentation, let's see.

**Comment by siavash-khodadadeh** [comment]
That is a very interesting idea to explore. With regards to implementation, you need to put every category in a different folder and then give the directory which contains all of these directories as dataset root. Then you also need to rewrite the part which performs augmentation to generate two images by the GAN which are conditioned on the same class or are close in z space. 
This should be done at this function: https://github.com/siavash-khodadadeh/MetaLearning-TF2.0/blob/master/tf_datasets.py#L139
I am closing the issue.
